SELECT * FROM EMP;
SELECT * FROM DEPT;

--NAME OF EMP WHERE DEPT_NO=20
SELECT ENAME FROM EMP WHERE DEPTNO=20;

--NAME OF EMP EARNING MORE THAN 3000
SELECT ENAME FROM EMP WHERE SAL>3000;

-- DETAILS OF EMP IF THEIR ANN SAL IS MORE THAN 12000
SELECT * FROM EMP WHERE (SAL*12)>12000;

--DETAILS OF EMP IF THEY ARE HIRED AFTER 1980-10-10
SELECT * FROM EMP WHERE HIREDATE > '1980-12-31';

--NAME AND ANN_SAL OF EMP IF THEY ARE HIRED BEFORE 1987
SELECT ENAME , SAL*12 AS ANN_SAL FROM EMP WHERE HIREDATE< '1987-01-01';

--NAME BUT SHOULD NOT WORK IN DEPTNO 30
SELECT ENAME FROM EMP WHERE DEPTNO!=30;
SELECT ENAME FROM EMP WHERE DEPTNO<>30;

--DETAILS OF EMP IF THEY ARE WORKING AS SALESMAN AND THEIR SALARY IS GREATER THAN 2000
SELECT * FROM EMP WHERE JOB='SALESMAN' AND SAL>2000;

--NAME OF EMP WORKING AS MANAGER AND SAL>2000 AND HIRED AFTER 1980 
SELECT ENAME FROM EMP WHERE JOB='MANAGER' AND SAL>2000 AND HIREDATE > '1980-12-31';

--DETAILS OF EMP WHO IS HIRED IN YEAR OF 1981
SELECT * FROM EMP WHERE HIREDATE>='1981-01-01' AND HIREDATE <='1981-12-31';

--NAME AND HALF TIME SAL OF EMP IF THEIR ANNUAL SAL IS MORE THAN 8000 AND HIRED AFTER 1981 BEFORE 1988
SELECT ENAME, SAL*6 AS HALF_TIME_SAL FROM EMP WHERE SAL*12 > 8000 
AND HIREDATE>'1981-12-31' AND HIREDATE<'1988-01-01';

--DETAILS OF EMP IF WORKING AS CLERK OR ANALYST
SELECT * FROM EMP WHERE JOB='CLERK' OR JOB='ANALYST';

--DETAILS OF EMP IF WORKING AS CLERK OR ANALYST BUT THEIR SAL > 2000
SELECT * FROM EMP WHERE (JOB='CLERK' OR JOB='ANALYST') AND SAL>2000 ;

--NAME OF EMP HIRED AFTER 1978 AND BEFORE 1987 AND EARNING>2000 WORKING IN DEPTNO 10 OR 30 AS CLERK OR MANAGER OR SALESMAN
SELECT ENAME FROM EMP WHERE HIREDATE>'1978-12-31'  AND HIREDATE<'1987-01-01' AND SAL>2000 
AND (DEPTNO=10 OR DEPTNO=30) AND (JOB='CLERK' OR JOB='MANAGER' OR JOB='SALESMAN');

--DETAILS OF EMP EXCEPT EMP WORKING AS SALESMAN
SELECT * FROM EMP WHERE NOT JOB='SALESMAN';

--DETAILS OF EMP IF THEY ARE HIRED IN THE YEAR OF 1981 BUT NOT WORKING WORKING AS MANAGER OR CLERK
SELECT * FROM EMP WHERE HIREDATE>='1981-01-01' AND HIREDATE <='1981-12-31' AND NOT(JOB='MANAGER' OR JOB='CLERK');

--DETAILS OF EMP WORKING IN DEPTNO 10,20,30,40
SELECT * FROM EMP WHERE DEPTNO=10 OR DEPTNO=20 OR DEPTNO=30 OR DEPTNO=40 ;
SELECT * FROM EMP WHERE DEPTNO IN (10,20,30,40);

--DETAILS OF EMP WORKING AS MANAGER OR PRESIDENT BUT IF THEY ARE EARNING > 2000 IN DEPTNO 20 OR 30
SELECT * FROM EMP WHERE JOB IN ('MANAGER','PRESIDENT') AND SAL>2000 AND DEPTNO IN (20,30);

--NAME AND HIREDATE OF EMP WORKING IN DEPTNO 20 OR 30 BUT THEY ARE NOT WORKING AS CLERK OR MANAGER AND HIRED AFTER 1982
SELECT ENAME,HIREDATE FROM EMP WHERE DEPTNO IN(20,30) AND JOB NOT IN('CLERK','MANAGER') AND HIREDATE>'1982-12-31';

--DETAILS OF EMP EARNING IN RANGE OF 1000 OR 5000 AS CLERK OR MANAGER
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 5000 AND JOB IN ('CLERK','MANAGER');

--DETAILS OF EMP HIRED AFTER 1976 AND BEFORE 1987 AND EARNING MORE THAN 2000 AND LESS THAN 5000
SELECT * FROM EMP WHERE( HIREDATE BETWEEN '1977-01-01' AND '1986-12-31') AND (SAL BETWEEN 2001 AND 4999);

--DETAILS OF EMP IF THEY ARE WORKING AS MANAGER BUT THEY ARE NOT EARNING IN THE RANGE 1000 TO 3000
SELECT * FROM EMP WHERE JOB='MANAGER' AND SAL NOT BETWEEN 1000 AND 3000;

--DETAILS OF EMP IF THEY ARE NOT EARNING COMMISSION
SELECT * FROM EMP WHERE COMM IS NULL OR COMM=0;

--DETAILS OF EMP WHO DON'T HAVE REPORTING MANAGER
SELECT * FROM EMP WHERE MGR IS NULL;

--DETAILS OF EMP WHO ARE EARNING COMMISSION
SELECT * FROM EMP WHERE COMM IS NOT NULL AND COMM>0.0;

--DETAILS OF EMP IF THEY HAVE REPORTING MANAGER BUT NOT EARNING COMM OR THEY ARE MANAGERS OR SALESMAN
SELECT * FROM EMP WHERE (MGR IS NOT NULL) AND (COMM IS NULL OR COMM=0) AND (JOB IN ('MANAGER','SALESMAN'));

--DETAILS OF EMP IF THEY HAVE CHARACTER 'MAN' IN THEIR JOB
SELECT * FROM EMP WHERE JOB LIKE '%MAN%' ;

--DETAILS OF EMP WHERE NAME CONTAINS A AS THEIR SECOND CHARACTER
SELECT * FROM EMP WHERE ENAME LIKE '_A%';

--DETAILS OF EMP IF THEY ARE HAVING CHAR A OR S IN THEIR JOB AND SALARY STARTING WITH DIGIT OF 50
SELECT * FROM EMP WHERE (JOB LIKE '%A%' OR JOB LIKE '%S%') AND CAST(SAL AS VARCHAR(20)) LIKE '50%';

--DETAILS OF EMP IF THEY ARE HIRED IN THE YEAR OF 1981 AND THEY ARE HAVING 3 DIGIT SALARY
SELECT * FROM EMP WHERE CAST(HIREDATE AS VARCHAR(20)) LIKE '1981%' AND CAST(SAL AS VARCHAR(20)) LIKE '______';

--DETAILS OF NAME AND HIREDATE OF EMP IF THEY HAVE COMM AND WORK AS MANAGER/SALESMAN AND 2 CONSECUTIVE L S IN THEIR NAME 
--IF SALARY IS MORE THAN 2000 AND HIRED IN YEAR 1981
SELECT ENAME,HIREDATE FROM EMP WHERE COMM IS NOT NULL AND JOB IN ('MANAGER','SALESMAN') AND ENAME LIKE '%LL%' AND SAL>2000
AND CAST(HIREDATE AS VARCHAR(20)) LIKE '1981%' ;

--DETAILS OF EMP USING CONC
SELECT 'MR. '||ENAME||' '||JOB AS NAME FROM EMP;

--DETAILS TO DISPLAY STATEMENT FOR EMP WHERE THEY EARN SALARY  //SMITH IS A CLERK WHO EARNS 800
SELECT ENAME ||' IS A '||JOB||' WHO EARNS '||SAL FROM EMP;

--TO DISPLAY OFFICIAL MAILID
SELECT EMPNO || ENAME || '@COMPANY.IN' FROM EMP;

--DETAILS OF EMP
SELECT LENGTH(ENAME)FROM EMP;

--DETAILS OF EMP
SELECT MAX(SAL) FROM EMP;
