SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT MIN(ENAME) FROM EMP;

--NO OF EMPLOYEES WORKING IN DEPTNO 20
SELECT COUNT(*) FROM EMP WHERE DEPTNO=20;

--DISPLAY MAX AND TOTAL SAL OF EMP HIRED AFTER 1980
SELECT MAX(SAL),SUM(SAL) FROM EMP WHERE HIREDATE > '1980-12-31';

--NO OF UNIQUE SALARIES PRESENT
SELECT COUNT(DISTINCT SAL ) FROM EMP;

--AVG SALARY TO PAY WHO EARNS IN RANGE OF 1000 TO 3000 AND HIRED IN THE YEAR OF 1981
SELECT AVG(SAL) FROM EMP WHERE SAL BETWEEN 1000 AND 3000 AND CAST(HIREDATE AS VARCHAR(20)) LIKE '1981%';

--NO OF EMP WORKING IN EACH DEPARTMENT
SELECT DEPTNO,COUNT(*) FROM EMP GROUP BY DEPTNO;

--NO OF EMP WORKING AS SALESMAN IN EACH DEPARTMENT
SELECT DEPTNO,COUNT(*) FROM EMP WHERE JOB='SALESMAN' GROUP BY DEPTNO;

--MAX SAL OF EMP WORKING IN EACH JOB IF THEIR SALARY IS MORE THAN 2000 AND THEY HAVE CHAR 'A' IN THEIR JOB
SELECT MAX(SAL),JOB FROM EMP WHERE SAL>2000 AND JOB LIKE '%A%' GROUP BY JOB ;

--UNIQUE SALARY
SELECT COUNT(SAL),SAL FROM EMP GROUP BY SAL;

--NO OF EMP ALONG WITH THEIR TOTAL SAL IN EACH DEPT IF THEY HAVE REPORTING MANAGER BUT NOT EARNING COMM AND HIRED IN 1982
SELECT COUNT(*),SUM(SAL),DEPTNO FROM EMP WHERE MGR IS NOT NULL AND COMM IS NULL AND CAST(HIREDATE AS VARCHAR(20)) 
LIKE '1982%' GROUP BY DEPTNO;

--NO OF EMP IN EACH DEPT IF THERE ARE ATLEAST 2 EMP IN EACH DEPT 
SELECT COUNT(*),DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>=2;

--NO OF SALESMAN WORKING IN EACH DEPT IF THEY ARE EARNING MORE THAN 1100 AND THEIR MAX SAL IS MORE THAN 2000
SELECT COUNT(*),DEPTNO FROM EMP WHERE JOB='SALESMAN' AND SAL>1100 GROUP BY DEPTNO HAVING MAX(SAL)>2000;

--MAX SAL OF EMP WORKING IN EACH DEPT IF THEIR MAX SAL IS MORE THAN 2000 AND LESS THAN 5001 AND THEY ARE WORKING AS CLERK OR MANAGER
SELECT MAX(SAL),DEPTNO FROM EMP WHERE JOB IN ('CLERK','MANAGER') GROUP BY DEPTNO HAVING MAX(SAL) BETWEEN 2001 AND 5000;

--REPEATED SALARY
SELECT SAL FROM EMP GROUP BY SAL HAVING COUNT(SAL)>1; 

--AVG SAL NEEDED TO PAY FOR EMP WHO WORKS AS MANAGER IF SAL>2000 AND THEY ARE HAVING TOTAL SAL MORE THAN 3000 IN EACH DEPT
SELECT AVG(SAL),DEPTNO FROM EMP WHERE JOB='MANANGER' AND SAL>2000 GROUP BY DEPTNO HAVING SUM(SAL)>3000;

--DET OF EMP WHO EARN MORE THAN SMITH
SELECT * FROM EMP WHERE SAL >(SELECT SAL FROM EMP WHERE ENAME='SMITH');

--DET OF EMP EARNING LESS THAN JONES AND HIRED AFTER 1980
SELECT * FROM EMP WHERE HIREDATE>'1980-12-31' AND SAL <(SELECT SAL FROM EMP WHERE ENAME='JONES');

--NAME AND HIREDATE OF EMP HIRED AFTER ALLEN AND EARNING MORE THAN JONES
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='ALLEN') 
AND SAL>(SELECT SAL FROM EMP WHERE ENAME='JONES');

--NAME AND HIREDATE OF EMP WHO'S NAME ENDS WITH S AND HIRED AFTER JAMES
SELECT ENAME, HIREDATE FROM EMP WHERE ENAME LIKE '%S' AND HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='JAMES') ;

--NAME OF EMP WORKING IN SAME DEPT AS JAMES AND EARNING MORE THAN ADAMS AND 
--WORKING IN THE SAME ROLE AS MILLER AND HIRED AFTER MARTIN
SELECT ENAME FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='JAMES') AND 
SAL>(SELECT SAL FROM EMP WHERE ENAME='ADAMS') AND
JOB=(SELECT JOB FROM EMP WHERE ENAME='MILLER') AND
HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='MARTIN');

--NO OF EMP EARNING MORE THAN SMITH AND LESS THAN MARTIN
SELECT COUNT(*) FROM EMP WHERE SAL>(SELECT SAL FROM EMP WHERE ENAME='SMITH') AND 
SAL<(SELECT SAL FROM EMP WHERE ENAME='MARTIN');

--DET OF EMP WORKING IN THE LOCATION OF NEW YORK
SELECT * FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');

--LOC OF ALLEN
SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='ALLEN');

--DET OF EMP IF THEY ARE HIRED AFTER THE EMP WHO IS EARNING MORE THAN 3000 AND THEY ARE WORKING IN THE LOC OF BOSTON
SELECT * FROM EMP WHERE HIREDATE>(SELECT HIREDATE FROM EMP WHERE SAL>3000) 
AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='BOSTON');

--DET OF EMP WORKING IN SAME DESIGNATION AS MILLER AND WORKS IN LOC NEW YORK
SELECT * FROM EMP WHERE JOB=(SELECT JOB FROM EMP WHERE ENAME='MILLER')
AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');

--NO OF EMP WORKING AS CLERK IN THE SAME DEPTNO AS SMITH AND EARNING MORE THAN KING HIRED AFTER MARTIN IN THE LOC BOSTON
SELECT COUNT(*) FROM EMP WHERE JOB='CLERK' AND DEPTNO=(SELECT DEPTNO FROM EMP WHERE ENAME='SMITH')
AND SAL>(SELECT SAL FROM EMP WHERE ENAME='KING') AND HIREDATE>(SELECT HIREDATE FROM EMP WHERE ENAME='MARTIN')
AND DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='BOSTON');

--DNAME OF CLERK
-- SELECT DNAME FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE JOB='CLERK');
SELECT DNAME FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE JOB='CLERK');

--DET OF EMP WHO IS EARNING MAX SAL
SELECT * FROM EMP WHERE SAL =(SELECT MAX(SAL) FROM EMP );

--DET OF EMP WHO IS EARNING 2ND MAX SAL
SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP WHERE SAL <(SELECT MAX(SAL) FROM EMP));
SELECT * FROM EMP WHERE SAL=(SELECT DISTINCT SAL FROM EMP ORDER BY SAL DESC OFFSET 1 LIMIT 1);

--DET OF EMP WHO IS EARNING 3RD MAX SAL
SELECT MAX(SAL) FROM EMP
WHERE SAL < ( SELECT MAX(SAL)
FROM EMP
WHERE SAL < ( SELECT MAX(SAL)
FROM EMP));

--DET OF EMP WHO IS EARNING 3RD MIN SAL
SELECT * FROM EMP WHERE SAL = (SELECT MIN(SAL) FROM EMP 
WHERE SAL >(SELECT MIN (SAL) FROM EMP 
WHERE SAL >(SELECT MIN(SAL) FROM EMP)));

--LOC OF EMP GETTING 2ND MAX SAL
-- SELECT LOC FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP 
-- WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE SAL <(SELECT MAX(SAL) FROM EMP)));

SELECT LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP
WHERE SAL IN (SELECT MAX(SAL) FROM EMP WHERE SAL < (SELECT MAX(SAL) FROM EMP)));

--DET OF EMP EARNING MORE THAN THE EMP WHO IS HAVING CONSECUTIVE 2 L IN HIS NAME AND THEY ARE WORKING IN LOC OF NEW YORK
SELECT * FROM EMP WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE ENAME LIKE '%LL%') AND
DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');

SELECT * FROM EMP WHERE SAL > ALL(SELECT SAL FROM EMP WHERE ENAME LIKE '%LL%') AND
DEPTNO IN (SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');

--DET OF EMP EARNING MORE THAN CLERKS
-- SELECT * FROM EMP WHERE SAL >(SELECT SAL FROM EMP WHERE JOB='CLERK');
SELECT * FROM EMP WHERE SAL > ALL(SELECT SAL FROM EMP WHERE JOB='CLERK');

--DET OF EMP EARNING MORE THAN ANY OF THE CLERK / ATLEAST ONE CLERK
SELECT * FROM EMP WHERE SAL > ANY(SELECT SAL FROM EMP WHERE JOB='CLERK');

--DET OF EMP EARNING MORE THAN SALESMAN AND LESS THAN ATLEAST A PRESIDENT 
SELECT * FROM EMP WHERE SAL > ALL(SELECT SAL FROM EMP WHERE JOB='SALESMAN') AND 
SAL < ANY(SELECT SAL FROM EMP WHERE JOB='PRESIDENT');

--DET OF EMP WHO ARE HIRED AFTER THE EMP WORKING IN THE LOC OF NEW YORK AND 
--THEY ARE EARNING MORE THAN THE EMPLOYEES WHO IS HAVING CHAR A  OR S IN HIS NAME

SELECT * FROM EMP WHERE HIREDATE >ALL(SELECT HIREDATE FROM EMP WHERE DEPTNO IN 
(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK') ) 
AND SAL > ALL( SELECT SAL FROM EMP WHERE ENAME LIKE '%A%' OR ENAME LIKE '%S%');

--DET OF SMITH'S MANAGER
SELECT * FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='SMITH');

--DNAME OF ALLEN'S MANAGER
SELECT DNAME FROM DEPT WHERE DEPTNO=(SELECT DEPTNO FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='ALLEN'));

--WARD'S MANAGER'S MANAGER
SELECT * FROM EMP WHERE EMPNO =(SELECT MGR FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='WARD'));

--DET OF EMPS REPORTING TO KING
SELECT * FROM EMP WHERE MGR=(SELECT EMPNO FROM  EMP WHERE ENAME='KING');

--DET OF EMPS REPORTING TO JONES' MANAGER 
SELECT * FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='JONES'));
SELECT * FROM EMP WHERE MGR=(SELECT MGR FROM EMP WHERE ENAME='JONES');

--DET OF EMP REPORTING TO WARD'S MANAGER'S MANAGER
SELECT * FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP 
WHERE EMPNO=(SELECT MGR FROM EMP 
WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='WARD')));

SELECT * FROM EMP WHERE MGR=(SELECT MGR FROM EMP 
WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='WARD'));

--10TH MAX SAL
SELECT DISTINCT SAL
FROM EMP
ORDER BY SAL DESC
OFFSET 9 LIMIT 1;
/*SELECT ROWNUM /ROWID FROM EMP;*/
-- QUERY TO DISPLAY 10TH MAXIMUM SALARY

-- SELECT SAL
-- FROM (
--         SELECT ROWNUM SL_NO, SAL
--         FROM (
--                 SELECT DISTINCT SAL
--                 FROM EMP
--                 ORDER BY SAL DESC
--              )
--      )
-- WHERE SL_NO = 10;
-- REP TO SMITH'S MANAGER'S MANAGER
SELECT * FROM EMP WHERE MGR =(SELECT EMPNO FROM EMP
WHERE EMPNO=(SELECT MGR FROM EMP 
WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='SMITH'
)));
