--NTH/4TH MAX SALARY
SELECT E1.SAL FROM EMP E1 WHERE 3 /*N-1*/ IN (SELECT COUNT(DISTINCT E2.SAL)
FROM EMP E2 WHERE E1.SAL<E2.SAL);

--10TH MIN SALARY
SELECT E1.SAL FROM EMP E1 WHERE 9 IN (SELECT COUNT(DISTINCT E2.SAL) FROM EMP E2 WHERE E1.SAL>E2.SAL);

--LOC OF EMP EARNING 8TH MAX SAL
SELECT LOC FROM DEPT WHERE DEPTNO IN (SELECT DEPTNO FROM EMP E1 WHERE 7 IN (SELECT COUNT(DISTINCT E2.SAL)
FROM EMP E2 WHERE E1.SAL<E2.SAL));

--3RD & 4TH MAX SAL
SELECT E1.SAL FROM EMP E1 WHERE (SELECT COUNT(DISTINCT E2.SAL)
FROM EMP E2 WHERE E1.SAL<E2.SAL) IN (2,3);

--1ST 5 MAX SAL
SELECT DISTINCT E1.SAL FROM EMP E1 WHERE (SELECT COUNT(DISTINCT E2.SAL)
FROM EMP E2 WHERE E1.SAL<E2.SAL) BETWEEN 0 AND 4 ORDER BY E1.SAL DESC;

--MAX SAL OF EACH DEP
SELECT MAX(SAL),DEPTNO FROM EMP GROUP BY DEPTNO;

--2ND MAX SAL OF EACH DEP
SELECT MAX(E1.SAL),DEPTNO FROM EMP E1 WHERE SAL<(SELECT MAX(E2.SAL) FROM EMP E2
WHERE E1.DEPTNO=E2.DEPTNO) GROUP BY E1.DEPTNO;

--3RD MAX SAL OF EACH DEP
SELECT MAX(E1.SAL), E1.DEPTNO FROM EMP E1 WHERE SAL < (SELECT MAX(E2.SAL) FROM EMP E2
WHERE E1.DEPTNO = E2.DEPTNO 
AND SAL < (SELECT MAX(E3.SAL) FROM EMP E3 WHERE E1.DEPTNO = E3.DEPTNO))
GROUP BY E1.DEPTNO;

--DET OF EMP WHOSE SAL IS MORE THAN THE AVG SAL OF THEIR OWN DEPT
SELECT * FROM EMP E1 WHERE SAL>(SELECT AVG(E2.SAL) FROM EMP E2
WHERE E1.DEPTNO=E2.DEPTNO);

--EMP AND THEIR DEP DETAILS
SELECT * FROM EMP CROSS JOIN DEPT; --INVALID
SELECT * FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;
SELECT * FROM EMP JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO;

--DET OF EMP ALONG WITH THEIR LOC IF EMP ARE EARNING MORE THAN 2000
SELECT EMP.* , LOC FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO WHERE SAL>2000;

--DEPT NAME , ENAME , SAL IF THEY ARE WORKING IN LOC OF NEW YORK AND THYE ARE EARNING MORE THAN CLERK
SELECT DNAME,ENAME, SAL FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO WHERE LOC='NEW YORK' AND 
SAL>ALL(SELECT SAL FROM EMP WHERE JOB='CLERK');

--DET OF DEP ALONG WITH THEIR SAL OF EMP IF THEY ARE WORKING IN DEPTNO 20 AND 
--THEY ARE EARNING MORE THAN THE EMP WHO IS HIRED AFTER THE EMP WHO IS WORKING IN LOC OF CHICAGO
SELECT DEPT.* ,SAL FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO WHERE EMP.DEPTNO=20 
AND SAL>ALL(SELECT SAL FROM EMP 
WHERE HIREDATE >ALL(SELECT HIREDATE FROM EMP WHERE DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='CHICAGO')));

--DET OF EMP EARNING ALONG WITH DNAME IF THEY ARE HIRED AFTER ATLEAST A CLERK AND THEY ARE WORKING
--IN ACCOUNTING DEPT AND IF THEY HAVE REPORTING MANAGER
SELECT EMP.* ,DNAME FROM EMP INNER JOIN DEPT ON EMP.DEPTNO=DEPT.DEPTNO WHERE HIREDATE >ANY(SELECT HIREDATE FROM EMP
WHERE JOB='CLERK') AND DNAME='ACCOUNTING' AND MGR IS NOT NULL;

--DET OF ALLN'E MANAGER
SELECT * FROM EMP WHERE EMPNO=(SELECT MGR FROM EMP WHERE ENAME='ALLEN');

--DET OF EMP REP TO KING
SELECT * FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME='KING');

--DISPLAY EMP AND THEIR MANAGER DET
SELECT E1.* ,E2.* FROM EMP E1 JOIN EMP E2 ON E1.MGR=E2.EMPNO;

--NAME AND HIREDATE OF EMP AND THEIR MANAGERS IF EMP ARE EARNING MORE THAN THEIR MANAGERS
--AND MANANGERS ARE HIRED AFTER 1980
SELECT E1.ENAME ,E1.HIREDATE , E2 .ENAME , E2.HIREDATE FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EMPNO WHERE E1.SAL>E2.SAL
AND E2.HIREDATE > '1980-12-31';

--NAME AND ANNUAL SAL OF EMP AND THEIR MANAGERS IF EMP AND MANAGERS ARE WORKING
-- IN THE SAME JOB AND EMP ARE EARNING MORE THAN THE EMP
--WHO IS HAVING CHAR  A IN HIS NAME
SELECT E1.ENAME ,E1.SAL *12  , E2 .ENAME , E2.SAL *12 FROM EMP E1 JOIN EMP E2
ON E1.MGR=E2.EMPNO WHERE E1.JOB=E2.JOB
AND E1.SAL> ALL (SELECT SAL FROM EMP WHERE ENAME LIKE '%A%');

--NAME OF EMP AND THEIR MANAGERS AND THEIR MANAGER'S MANANGER
SELECT  E1.ENAME AS EMPLOYEE,E2.ENAME AS MANAGER, E3.ENAME AS MANAGERS_MANAGER
FROM EMP E1 JOIN EMP E2 ON E1.MGR = E2.EMPNO
JOIN EMP E3 ON E2.MGR = E3.EMPNO;

--NAME OF EMP AND THEIR MANAGERS IF EMP ARE EARNING MORE THAN ALLEN AND MANAGERS ARE HIRED AFTER THEIR MANAGER
--AND EMP AND MANAGERS ARE WORKING IN THE SAME JOB AND MANAGERS ARE WORKING IN THE LOC OF NEW YORK
SELECT  E1.ENAME AS EMPLOYEE,E2.ENAME AS MANAGER 
FROM EMP E1 JOIN EMP E2 ON E1.MGR = E2.EMPNO
JOIN EMP E3 ON E2.MGR = E3.EMPNO WHERE E1.SAL>(SELECT SAL FROM EMP WHERE ENAME='ALLEN')
AND E2.HIREDATE>E3.HIREDATE AND E1.JOB=E2.JOB AND E2.DEPTNO=(SELECT DEPTNO FROM DEPT WHERE LOC='NEW YORK');

--NAME OF EMP AND THEIR MANAGERS ALONG WITH MANAGER'S MANAGER NAME ALONG WITH THEIR DEPARTMENT NAME
SELECT  E1.ENAME AS EMPLOYEE, D1.DNAME AS EMP_DEP ,E2.ENAME AS MANAGER ,D2.DNAME AS MAN_DEP ,
E3.ENAME AS MANAGERS_MANAGER , D3.DNAME AS MAN_MAN_DEP 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO
JOIN EMP E3 ON E2.MGR = E3.EMPNO
INNER JOIN DEPT D1 ON E1.DEPTNO=D1.DEPTNO
INNER JOIN DEPT D2 ON E2.DEPTNO=D2.DEPTNO
INNER JOIN DEPT D3 ON E3.DEPTNO=D3.DEPTNO;

--LOC OF SALESMAN'S MANAGER'S MANAGER
SELECT D3.LOC AS MAN_MAN_DEP 
FROM EMP E1 
JOIN EMP E2 ON E1.MGR = E2.EMPNO
JOIN EMP E3 ON E2.MGR = E3.EMPNO
INNER JOIN DEPT D3 ON E3.DEPTNO=D3.DEPTNO WHERE E1.JOB='SALESMAN';

--
SELECT * FROM EMP;

--
SELECT * FROM EMP;
